### ISSUE TITLE
タブレット対応

### ISSUE THREAD

**Issue by h-fujioka11** [h-fujioka11/calldoc#7]

**Comment by h-fujioka11** [comment]
＊スマホの確認時にセクション間のマージンも要確認
<img width="463" alt="スクリーンショット 2020-11-04 15 59 09" src="https://user-images.githubusercontent.com/43980392/98079258-d61c6b80-1eb6-11eb-8c5b-c320f1c7d5e0.png">

**Comment by y-onishi4400** [comment]
以下ブランチで、レイアウトの調整を行いました。
https://github.com/h-fujioka11/calldoc/commit/73f10b7c3bb810f5385244077e01f79bd7b405c1
